# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb261c51b0231245ba6fbcf04ef624844ab1c29bed652a46f72ef3104c695654c28c3084291307ef0860990648dd9c4b1cd377fb6e832d091c38170fc960ac91

test:
  secret_key_base: 41fef960e61cdb0526fbe51457641bb184bd9035d1fb63f444b2374a9d8e25ae583923e6dd851e338ae7a4074e2cff332c746a4c71c349940d2029d30f2249fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
